package ventanas;

import Arbol.ArbolBinario;
import Arbol.NodoArbol;
import javax.swing.JOptionPane;
import listas.lista.Lista;
import quiz2.arvhivo.AccestTxt;

/**
 *
 * @author dilan
 */
public class VentanaM extends javax.swing.JFrame {

    private String datos = "";
    private ArbolBinario arbol;
    
    /**
     * Creates new form VentanaM
     */
    public VentanaM() {
        this.arbol = null;
        initComponents();
        this.setTitle("Arbol de letras");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pathTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        palabras = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        buscarPalabra = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Cargar txt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        pathTxt.setText("../quiz2/src/quiz2/arvhivo/palabras.txt");
        pathTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTxtActionPerformed(evt);
            }
        });
        jPanel1.add(pathTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 270, -1));

        jLabel1.setText("Path txt:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        palabras.setColumns(20);
        palabras.setRows(5);
        jScrollPane1.setViewportView(palabras);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, -1, 380));

        jButton2.setText("Mostrar Todo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));
        jPanel1.add(buscarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 160, -1));

        jButton3.setText("Buscar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jLabel2.setText("Busca palabra:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path = pathTxt.getText();
        AccestTxt txt = new AccestTxt(path);
        this.datos = txt.readTxt();
        this.arbol = new ArbolBinario();
        String[] linea = datos.split("\n");
        NodoArbol aux = arbol.getRaiz();
        Boolean agregado = false;
        for (int i = 0; i < linea.length; i++) {
            String[] data = linea[i].split(",");
            for (int j = 0; j < data.length; j++) {
                data[j] = data[j].replace(" ", "");
//                if (data[j].length() > 1 && !"null".equals(data[j])  && !"left".equals(data[j]) && !"right".equals(data[j])) {
//                    JOptionPane.showMessageDialog(null, "Error al introducir los datos del txt, verifique que este bien escrito");
//                    return;
//                }
            }
            if (!agregado) {
                arbol.setRaiz(new NodoArbol(data[0]));
                agregado = true;
            }else{
                int dirrecion = -1;
                aux = arbol.encontrarNodo(data[1], arbol.getRaiz());
                if (data[2].equals("left")) {
                    dirrecion = 0;
                }else if(data[2].equals("right")){
                    dirrecion = 1;
                }else{
                    JOptionPane.showMessageDialog(null, "Error");
                    return;
                }
                arbol.agregar(aux, data[0],dirrecion);
            }          
        }
        arbol.buscarPalabra();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (arbol == null) {
            JOptionPane.showMessageDialog(null, "No se ha cargado txt");
        }
        Lista palabrasFinds = arbol.getPalabras();
        String frase = "";
        for (int i = 0; i < palabrasFinds.length(); i++) {
            frase += palabrasFinds.mostrarIndice(i) + "\n";
        }
        palabras.setText(frase);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pathTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarPalabra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea palabras;
    private javax.swing.JTextField pathTxt;
    // End of variables declaration//GEN-END:variables
}
